In [1]:
!pip install numpy

^C


In [3]:
import numpy as np

In [4]:
l = [1,2,3,4]

In [5]:
arr1 = np.array(l)

In [8]:
print(arr1)
type(arr1)

[1 2 3 4]


numpy.ndarray

In [11]:
arr2 = np.array([5,6,7,8])

In [12]:
arr2

array([5, 6, 7, 8])

In [13]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [14]:
arr1 - arr2

array([-4, -4, -4, -4])

In [ ]:
# Write a function, to print
# *
# **
# ***
# ****
# *****

In [18]:
def pattern(n):
    for i in range(n):
        print("*"*i, end=" ")
        print()
        
pattern(5)

 
* 
** 
*** 
**** 


In [19]:
arr1

array([1, 2, 3, 4])

In [20]:
arr1.shape

(4,)

In [23]:
new_arr = np.array([[1,2,3],
                   [3,4,3]])

In [24]:
new_arr.shape

(2, 3)

In [25]:
new_arr

array([[1, 2, 3],
       [3, 4, 3]])

In [26]:
new_arr.T

array([[1, 3],
       [2, 4],
       [3, 3]])

### Broadcasting

In [33]:
new_arr  /  5

array([[0.2, 0.4, 0.6],
       [0.6, 0.8, 0.6]])

## Random Values

In [38]:
a = np.random.random((5,5))

In [41]:
b =  np.random.random((5,3))

In [44]:
res = np.dot(a,b)

In [45]:
res.shape

(5, 3)